apiVersion: v1
kind: Service
metadata:
  name: run-dashboard-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: run-dashboard-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: run-dashboard-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: run-dashboard-api
  template:
    metadata:
      labels:
        app: run-dashboard-api
    spec:
      containers:
      - name: run-dashboard-api
        image: docker.io/dlchoi91/run-dashboard-api:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: dbusername
          valueFrom:
            secretKeyRef:
              name: dbcred
              key: dbcred-user
        - name: dbpassword
          valueFrom:
            secretKeyRef:
              name: dbcred
              key: dbcred-password
        - name: dbhost
          valueFrom:
            secretKeyRef:
              name: dbcred
              key: dbcred-host
        - name: dbport
          valueFrom:
            secretKeyRef:
              name: dbcred
              key: dbcred-port
        - name: dbdbname
          valueFrom:
            secretKeyRef:
              name: dbcred
              key: dbcred-dbname
        - name: stravaclientid
          valueFrom:
            secretKeyRef:
              name: stravaclient
              key: client-id
        - name: stravaclientsecret
          valueFrom:
            secretKeyRef:
              name: stravaclient
              key: client-secret

